USE [Teste]
GO
IF NOT EXISTS( 
	SELECT	* 
	FROM	INFORMATION_SCHEMA.COLUMNS 
    WHERE	UPPER(TABLE_NAME) = UPPER('NOTAFISCALITEM') 
            AND UPPER(COLUMN_NAME) = UPPER('BaseIpi'))
BEGIN
	ALTER TABLE NOTAFISCALITEM ADD BaseIpi Decimal(18,5) NULL;
END

IF NOT EXISTS( 
	SELECT	* 
	FROM	INFORMATION_SCHEMA.COLUMNS 
    WHERE	UPPER(TABLE_NAME) = UPPER('NOTAFISCALITEM') 
            AND  UPPER(COLUMN_NAME) = UPPER('ValorIpi'))
BEGIN
	ALTER TABLE NOTAFISCALITEM ADD ValorIpi Decimal(18,5) NULL;
END

IF NOT EXISTS(
	SELECT * 
	FROM	INFORMATION_SCHEMA.COLUMNS 
    WHERE	UPPER(TABLE_NAME) = UPPER('NOTAFISCALITEM')
			AND  UPPER(COLUMN_NAME) = UPPER('AliquotaIpi'))
BEGIN
	ALTER TABLE NOTAFISCALITEM ADD AliquotaIpi Decimal(18,5) NULL;
END

IF NOT EXISTS(
	SELECT * 
	FROM	INFORMATION_SCHEMA.COLUMNS 
    WHERE	UPPER(TABLE_NAME) = UPPER('NOTAFISCALITEM')
			AND  UPPER(COLUMN_NAME) = UPPER('Desconto'))
BEGIN
	ALTER TABLE NOTAFISCALITEM ADD Desconto Decimal(18,5) NULL;
END


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Parametros](
	[PATHXMLNF] [varchar](500) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


INSERT INTO [dbo].[Parametros] ([PATHXMLNF]) VALUES ('C:\NotaFiscal')