USE [Teste]
GO
IF OBJECT_ID('dbo.P_CONSULTA_IMPOSTO_NOTA_FISCAL') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_CONSULTA_IMPOSTO_NOTA_FISCAL
    IF OBJECT_ID('dbo.P_CONSULTA_IMPOSTO_NOTA_FISCAL') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_CONSULTA_IMPOSTO_NOTA_FISCAL >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_CONSULTA_IMPOSTO_NOTA_FISCAL APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE P_CONSULTA_IMPOSTO_NOTA_FISCAL
AS
BEGIN
	
	 SELECT 
		 Cfop AS 'CFOP'
		,SUM(BaseIcms) AS 'Valor Total da Base de ICMS'
		,SUM(ValorIcms) AS 'Valor Total do ICMS'
		,SUM(BaseIpi) AS 'Valor Total da Base de IPI '
		,SUM(ValorIpi)	AS 'Valor Total do IPI'	
	FROM 
		NOTAFISCALITEM (NOLOCK)
	GROUP BY 
		 Cfop,BaseIcms,BaseIpi 
	  
END
GO
GRANT EXECUTE ON dbo.P_NOTA_FISCAL_ITEM TO [public]
GO