//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteImposto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TesteImposto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brinde.
        /// </summary>
        internal static string Brinde {
            get {
                return ResourceManager.GetString("Brinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Código do Produto da linha {0} em Branco..
        /// </summary>
        internal static string CampoCodigoProdutoBranco {
            get {
                return ResourceManager.GetString("CampoCodigoProdutoBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome do Produto da linha {0} em Branco..
        /// </summary>
        internal static string CampoNomeProdutoBranco {
            get {
                return ResourceManager.GetString("CampoNomeProdutoBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Valor do Produto da linha {0} em Branco..
        /// </summary>
        internal static string CampoValorProdutoBranco {
            get {
                return ResourceManager.GetString("CampoValorProdutoBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Produto.
        /// </summary>
        internal static string CodigoProduto {
            get {
                return ResourceManager.GetString("CodigoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe itens para esta nota..
        /// </summary>
        internal static string GridVazio {
            get {
                return ResourceManager.GetString("GridVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome Cliente em Branco..
        /// </summary>
        internal static string NomeBranco {
            get {
                return ResourceManager.GetString("NomeBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Produto.
        /// </summary>
        internal static string NomeProduto {
            get {
                return ResourceManager.GetString("NomeProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação efetuada com sucesso.
        /// </summary>
        internal static string OperacaoEfetuadaComSucesso {
            get {
                return ResourceManager.GetString("OperacaoEfetuadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        internal static string Pedidos {
            get {
                return ResourceManager.GetString("Pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione Estado Destino..
        /// </summary>
        internal static string SelecioneEstadoDestino {
            get {
                return ResourceManager.GetString("SelecioneEstadoDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione Estado Origem..
        /// </summary>
        internal static string SelecioneEstadoOrigem {
            get {
                return ResourceManager.GetString("SelecioneEstadoOrigem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
    }
}
